[package]
name = "quadtree"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = { version = "0.30.9", features=["x11"] }
env_logger = "0.10"
log = "0.4"
wgpu = "25.0"
pollster = "0.4"
rand = "0.9.1"